### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by AyoubEd-zz** [franc205/ArduinoDucky#1]
Any tutorial on doing this on windows!?
Thank you

**Comment by franc205** [comment]
Hi! You can use DFU-Programmer with the cmd, you just only have to download it from the official web. By the way, here is the link, you have to download the "dfu-programmer-win-X.X.X.zip" version. For everything else the procedure is the same.
Link: https://sourceforge.net/projects/dfu-programmer/files/dfu-programmer/0.7.0/
